name: Test Bash Script

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the main branch

jobs:
  test-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set up Python 3.10 (or the version your app requires)

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libpcre3-dev \
            zlib1g-dev \
            libssl-dev \
            libzstd-dev \
            cmake \
            ninja-build \
            git \
            python3-flask \
            wget \
            curl

      - name: Run the Bash script
        run: |
          chmod +x setup_pqc_nginx.sh  # Make the script executable
          ./setup_pqc_nginx.sh  # Run the script
  
      - name: Wait for Flask app to start
        run: |
          sleep 5  # Wait for the Flask app to start

      - name: Stop Flask app
        run: |
          kill $(cat flask.pid)  # Stop the Flask app using the saved process ID

      - name: Clean up
        run: |
          sudo systemctl stop nginx  # Stop Nginx
          sudo rm -rf /usr/local/nginx /opt/certs /etc/systemd/system/nginx.service  # Clean up installed files
  
