name: Test Bash Script

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the main branch

jobs:
  test-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set up Python 3.9 (or the version your app requires)

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libpcre3-dev \
            zlib1g-dev \
            libssl-dev \
            libzstd-dev \
            cmake \
            ninja-build \
            git \
            python3-flask \
            wget \
            curl

      - name: Run the Bash script
        run: |
          chmod +x setup.sh  # Make the script executable
          ./setup.sh  # Run the script

      - name: Verify Nginx is running
        run: |
          curl -I http://localhost:80  # Check if Nginx is serving HTTP
          curl -Ik https://localhost:443  # Check if Nginx is serving HTTPS

      - name: Verify Flask app is running
        run: |
          curl -I http://127.0.0.1:5000  # Check if the Flask app is running

      - name: Clean up
        run: |
          sudo systemctl stop nginx  # Stop Nginx
          sudo rm -rf /usr/local/nginx /opt/certs /etc/systemd/system/nginx.service  # Clean up installed files
